package com.baze3.features.judgmentStatusChange

object JudgementStatusChangeSQL {
    val findAll = "SELECT ID_PSP, ID_STATUSA_PSP, DATUM, JE_TRENUTNI FROM IZMENA_STATUSA_PSP"

    val findDetailsByPspId = """
        SELECT 
        IZMENA_STATUSA_PSP.ID_PSP, 
        IZMENA_STATUSA_PSP.ID_STATUSA_PSP, 
        IZMENA_STATUSA_PSP.DATUM, 
        IZMENA_STATUSA_PSP.JE_TRENUTNI,
        STATUS_PSP.NAZIV_STATUSA,
        PS_PRESUDA.BROJ_PREDMETA,
        PS_PRESUDA.DATUM
    FROM IZMENA_STATUSA_PSP
    JOIN STATUS_PSP ON IZMENA_STATUSA_PSP.ID_STATUSA_PSP = STATUS_PSP.ID_STATUSA
    JOIN PS_PRESUDA ON IZMENA_STATUSA_PSP.ID_PSP = PS_PRESUDA.ID_PSP
    WHERE IZMENA_STATUSA_PSP.ID_PSP = ?
    """.trimIndent()

    val findByCompositeKey = """
    SELECT 
        IZMENA_STATUSA_PSP.ID_PSP, 
        IZMENA_STATUSA_PSP.ID_STATUSA_PSP, 
        IZMENA_STATUSA_PSP.DATUM, 
        IZMENA_STATUSA_PSP.JE_TRENUTNI,
        STATUS_PSP.NAZIV_STATUSA,
        PS_PRESUDA.BROJ_PREDMETA,
        PS_PRESUDA.DATUM
    FROM IZMENA_STATUSA_PSP
    JOIN STATUS_PSP ON IZMENA_STATUSA_PSP.ID_STATUSA_PSP = STATUS_PSP.ID_STATUSA
    JOIN PS_PRESUDA ON IZMENA_STATUSA_PSP.ID_PSP = PS_PRESUDA.ID_PSP
    WHERE IZMENA_STATUSA_PSP.ID_PSP = ? AND IZMENA_STATUSA_PSP.ID_STATUSA_PSP = ?
""".trimIndent()

    val insert = "INSERT INTO IZMENA_STATUSA_PSP (ID_PSP, ID_STATUSA_PSP, DATUM) VALUES (?, ?, ?)"

    val update = "UPDATE IZMENA_STATUSA_PSP SET DATUM = ? WHERE ID_PSP = ? AND ID_STATUSA_PSP = ?"

    val delete = "DELETE FROM IZMENA_STATUSA_PSP WHERE ID_PSP = ? AND ID_STATUSA_PSP = ?"
}